#
# PROGRAM: assignment6.cc
# PROGRAMMER: Kenneth Harris
# LOGON ID:  z1733721
# DATE DUE: 3/24/2019
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment6.exe: assignment5.h assignment6.h assignment6main.cc
	g++ -Wall -g -std=c++11 assignment5.cc assignment6.cc assignment6main.cc -o assignment6.exe

clean:
	rm assignment6.exe



